# Generated by Django 5.0 on 2024-02-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockInOut', '0004_alter_employee_shift_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('devops', 'DevOps Engineer'), ('datasci', 'Data Scientist'), ('projmgr', 'Project Manager')], default='backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='clockInOut.employee'),
        ),
    ]
