# Generated by Django 5.0 on 2024-02-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockInOut', '0006_companytarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytarget',
            name='job_role',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('devops', 'DevOps Engineer'), ('datasci', 'Data Scientist'), ('projmgr', 'Project Manager')], max_length=20),
        ),
    ]
