# Generated by Django 5.0 on 2024-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockInOut', '0002_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='work_category',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Stationary', 'Stationary')], default='Stationary', max_length=10),
        ),
    ]
