# Generated by Django 5.0 on 2024-02-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockInOut', '0003_timeentry_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift_hours',
            field=models.CharField(choices=[('6-14', 'Morning Shift (6-14)'), ('14-22', 'Evening Shift (14-22)')], max_length=50),
        ),
    ]
